import type { Metadata } from "next";
import "./globals.css";
import Container from "@/components/common/Container";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={"bg-black relative h-screen overflow-hidden"}>
        <Container>{children}</Container>
        <Footer></Footer>
      </body>
    </html>
  );
}
